[tool.towncrier]
    package_dir = "source"
    filename = "source/news.rst"
    title_format = "{project_date}"
    issue_format = ":pr:`{issue}`"
    underlines = ["-", "~"]

   [[tool.towncrier.type]]
        directory = "new"
        name = "New Pages"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "update"
        name = "Page Updates"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "development"
        name = "User Guide Development Updates"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = false
